<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_preOpenSun</name>
   <tag></tag>
   <elementGuidId>c6714c5e-4d80-4b3c-92db-6a2c6203863a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control orange-border white-font ng-pristine ng-untouched ng-valid ng-isolate-scope ui-timepicker-input ng-valid-required ng-valid-time</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preOpenSun</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>locationInfos.locationHours.preOpenSun</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-timepicker</name>
      <type>Main</type>
      <value>timePickerOptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationInfoForm&quot;)/fieldset[@class=&quot;scheduler-border&quot;]/div[@class=&quot;control-group&quot;]/div[@class=&quot;col-md-12 col-sm-12 arrow-drop&quot;]/ng-include[@class=&quot;ng-scope&quot;]/table[@class=&quot;table table-hover table-light fg ng-scope&quot;]/thead[@class=&quot;top-bg-yt&quot;]/tr[2]/td[2]/input[@class=&quot;form-control orange-border white-font ng-pristine ng-untouched ng-valid ng-isolate-scope ui-timepicker-input ng-valid-required ng-valid-time&quot;]</value>
   </webElementProperties>
</WebElementEntity>
