<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BeerBoard</name>
   <tag></tag>
   <elementGuidId>6b88b81a-8ed9-4e34-a0ce-95d0008382f2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>goTo('beerboard')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                
                BeerBoard
              </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;tablesaw-enhanced&quot;]/body[@class=&quot;page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;div ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/header[@class=&quot;page-header ng-scope&quot;]/nav[@class=&quot;navbar mega-menu&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;clearfix navbar-fixed-top&quot;]/div[@class=&quot;nav-collapse collapse navbar-collapse navbar-responsive-collapse&quot;]/ul[@class=&quot;nav navbar-nav right&quot;]/li[@class=&quot;dropdown dropdown-fw ng-scope active open&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
